services:
  mysql:
    image: mysql:8.0
    container_name: gestion-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_db
      MYSQL_USER: gestion_user
      MYSQL_PASSWORD: gestion_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
